# Pre-commit hooks configuration
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            node_modules/.*|
            \.git/.*|
            \.pythonlibs/.*|
            __pycache__/.*|
            \.pytest_cache/.*|
            migrations/.*|
            \.venv/.*|
            tests/results/.*|
            static/.*|
            \.secrets\.baseline
          )$
