version: '3.8'

services:
  mina-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://mina_user:mina_password@postgres:5432/mina_db
      - REDIS_URL=redis://redis:6379/0
      - SESSION_SECRET=${SESSION_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=production
      - WORKERS=4
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mina-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mina_db
      - POSTGRES_USER=mina_user
      - POSTGRES_PASSWORD=mina_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mina-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mina-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - mina-app
    restart: unless-stopped
    networks:
      - mina-network

volumes:
  postgres_data:
  redis_data:

networks:
  mina-network:
    driver: bridge