name: 🧪 Mina CI Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Unit & E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          # Ensure Playwright is available for UI unit tests that rely on it
          pip install pytest-playwright
          python -m playwright install --with-deps chromium

      - name: Run pytest (unit + integration only)
        env:
          DATABASE_URL: sqlite:///:memory:
          SESSION_SECRET: test-secret-key
        run: |
          pytest tests/unit tests/integration -q --cov=. --cov-report=xml --cov-report=term || true

      - name: Upload coverage to Codecov (non-blocking)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  playwright:
    name: Run Playwright E2E
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=dot
